<a href="https://colab.research.google.com/github/Kin-theblackone/2045240193_NguyenHoangGiaNguyen_KT2/blob/main/2045240193_NguyenHoangGiaNguyen_KT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mã đề: AI-KT2-02 |
Họ tên SV: Nguyễn Hoàng Gia Nguyên |
MSSV: 2045240193

In [25]:
#Câu 1 - Bài toán thỏa mãn ràng buộc - Tô màu bản đồ

#Ma trận kề của đồ thị 6 đỉnh
G = [
    [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0], # A: D, F, I
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], # B: H, J
    [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0], # C: F, G, I, J, K
    [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0], # D: A, E, I
    [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1], # E: D, I, K, L
    [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], # F: A, C, I
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], # G: C, J
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], # H: B, J, K, L
    [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0], # I: A, C, D, E, F, K
    [0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0], # J: B, C, G, H, K
    [0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1], # K: C, E, H, I, J, L
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]  # L: E, H, K
]

#Danh sách 12 vùng từ A đến L
node = "ABCDEFGHIJKL"
t_ = {}
for i in range(len(G)):
    t_[node[i]] = i
#a
print("Câu a")
#Tính bậc của các đỉnh
degree = []
for i in range(len(G)):
    degree.append(sum(G[i]))

print("--- Bậc của từng vùng ---")
for i in range(len(node)):
    print(f"Vùng {node[i]}: Bậc {degree[i]}")

#Màu có thể sử dụng để tô cho các đỉnh
colorDict = {}
for i in range(len(G)):
  colorDict[node[i]] = ["Blue", "Red", "Yellow", "Green"]

#Sắp xếp các đỉnh theo thứ tự bậc
sortedNode = []
indeks = []
#use selection sort
for i in range(len(degree)):
    _max = 0
    j = 0
    for j in range(len(degree)):
        if j not in indeks:
            if degree[j] > _max:
                _max = degree[j]
                idx = j
    indeks.append(idx)
    sortedNode.append(node[idx])

print("\n--- Thứ tự cấc vùng được đưa vào tô màu ---")
print(" -> ".join(sortedNode))
#b
print("\n\nCâu b")
#Phần xử lý tô màu (sử dụng ít màu nhất có thể)
print("\n--- Bảng truy vết ---")
theSolution = {}
for n in sortedNode:
    if len(colorDict[n]) == 0:
        print(f"LỖI: Vùng {n} không còn màu để tô! Cần thêm màu vào danh sách.")
        theSolution[n] = "None"
        continue

    setTheColor = colorDict[n]
    theSolution[n] = setTheColor[0] # Lấy màu đầu tiên còn khả dụng

    print(f"Bước tô vùng {n}:")
    print(f"  - Màu gán: {theSolution[n]}")

    # Cập nhật loại bỏ màu vừa tô khỏi các vùng kề
    adjacentNode = G[t_[n]]
    affected_nodes = []
    for j in range(len(adjacentNode)):
        if adjacentNode[j] == 1 and (theSolution[n] in colorDict[node[j]]):
            colorDict[node[j]].remove(theSolution[n])
            affected_nodes.append(node[j])
    print(f"  - Vùng kề bị loại màu {theSolution[n]}: {', '.join(affected_nodes) if affected_nodes else 'Không có'}")
#c
print("\n\nCâu c")
print("\n--- Kết quả tô màu cuối cùng ---")
for t, w in sorted(theSolution.items()):
    print("Đỉnh", t, "=", w)

# Trích xuất các giá trị màu đã được sử dụng
used_colors = theSolution.values()

# Sử dụng set() để loại bỏ các màu trùng lặp
unique_colors = set(used_colors)

# Đếm số lượng màu thực tế đã dùng
num_colors_used = len(unique_colors)
print(f"\n=> Thuật toán đã dùng tổng cộng {num_colors_used} màu.")
print(f"=> Danh sách các màu đã dùng: {', '.join(unique_colors)}")

Câu a
--- Bậc của từng vùng ---
Vùng A: Bậc 3
Vùng B: Bậc 2
Vùng C: Bậc 5
Vùng D: Bậc 3
Vùng E: Bậc 4
Vùng F: Bậc 3
Vùng G: Bậc 2
Vùng H: Bậc 4
Vùng I: Bậc 6
Vùng J: Bậc 5
Vùng K: Bậc 6
Vùng L: Bậc 3

--- Thứ tự cấc vùng được đưa vào tô màu ---
I -> K -> C -> J -> E -> H -> A -> D -> F -> L -> B -> G


Câu b

--- Bảng truy vết ---
Bước tô vùng I:
  - Màu gán: Blue
  - Vùng kề bị loại màu Blue: A, C, D, E, F, K
Bước tô vùng K:
  - Màu gán: Red
  - Vùng kề bị loại màu Red: C, E, H, I, J, L
Bước tô vùng C:
  - Màu gán: Yellow
  - Vùng kề bị loại màu Yellow: F, G, I, J, K
Bước tô vùng J:
  - Màu gán: Blue
  - Vùng kề bị loại màu Blue: B, G, H
Bước tô vùng E:
  - Màu gán: Yellow
  - Vùng kề bị loại màu Yellow: D, L
Bước tô vùng H:
  - Màu gán: Yellow
  - Vùng kề bị loại màu Yellow: B
Bước tô vùng A:
  - Màu gán: Red
  - Vùng kề bị loại màu Red: D, F
Bước tô vùng D:
  - Màu gán: Green
  - Vùng kề bị loại màu Green: A, E, I
Bước tô vùng F:
  - Màu gán: Green
  - Vùng kề bị loại màu Green: C
B

**1d**
-
Câu trả lời:


*   Số màu ở câu c không phải là số màu ít nhất để tô bản đồ nà.
*   Cách tô màu:

Màu 1 (Blue): I, J, L

Màu 2 (Red): A, C, E, H

Màu 3 (Yellow): B, D, F, G, K

*   Thuật toán tham lam chỉ đưa ra quyết định tốt nhất cục bộ tại từng bước (luôn chọn màu khả dụng đầu tiên) mà thiếu tầm nhìn toàn cục.

In [34]:
#Câu 2. Học máy - K-Means & K-NN
#Phần A - K-Means
import numpy as np
from scipy.spatial.distance import cdist

# Khởi tạo dữ liệu theo đề bài
X = np.array([[1, 2], [2, -1], [3, 0], [7, 1], [6, -2], [8, 0]])
init_centers = np.array([[0, 0], [6, 0]])
n_cluster = 2

#Copy mã bên tuần 5:)))
def kmeans_predict_labels(X, centers):
    D = cdist(X, centers)
    print("a) Ma trận khoảng cách từ 6 điểm dữ liệu đến 2 tâm C1 và C2:")
    print(np.round(D, 2))
    return np.argmin(D, axis = 1)

def kmeans_update_centers(X, labels, n_cluster):
    centers = np.zeros((n_cluster, X.shape[1]))
    for k in range(n_cluster):
        Xk = X[labels == k, :]
        # Chỉ cập nhật tâm nếu cụm đó có phần tử (tránh lỗi chia cho 0)
        if len(Xk) > 0:
            centers[k,:] = np.mean(Xk, axis = 0)
    return centers

def kmeans_has_converged(centers, new_centers):
    return (set([tuple(a) for a in centers]) == set([tuple(a) for a in new_centers]))

#KQ
print("--- K-Means ---")

#Câu a
print("\nCâu a")
labels = kmeans_predict_labels(X, init_centers)
print("\nNhãn được phân cho 6 điểm (0 là C1, 1 là C2):")
print(labels)
print("\n- Giải thích về điểm P3:")
print("  Khoảng cách từ P3 đến C1 và C2 là bằng nhau (đều bằng 3.0).")
print("  Hàm np.argmin() có đặc điểm là sẽ lấy vị trí (index) đầu tiên chứa giá trị nhỏ nhất.")
print("  Vì C1 nằm ở vị trí số 0 nên P3 được xếp vào cụm C1.")

#Câu b
print("\n\nCâu b")
new_centers = kmeans_update_centers(X, labels, n_cluster)
print("\nb) Tọa độ chính xác của 2 tâm cụm mới sau vòng lặp đầu tiên:")
print(new_centers)

#Câu c
print("\n\nCâu c")
is_converged = kmeans_has_converged(init_centers, new_centers)
print(f"\nc) Thuật toán đã hội tụ chưa? -> {'Đã hội tụ' if is_converged else 'Chưa hội tụ'}")
print("- Giải thích:")
print("  Hàm kmeans_has_converged() sẽ kiểm tra xem tọa độ tâm cũ và tâm mới có giống y hệt nhau không.")
print("  Ở đây, tọa độ của 2 tâm đã thay đổi hoàn toàn nên thuật toán chưa thể dừng lại (chưa hội tụ).")

#Phần B - K-NN
print("\n\n--- K-NN ---")
# Khởi tạo dữ liệu
X_train = np.array([[2, 0], [2, 2], [3, 0], [2, 3], [4, 0], [4, 2]])
y_train = np.array([0, 1, 0, 1, 1, 0])
X_test = np.array([[0, 0]]) # Điểm q
labels = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6'] # Tên các điểm để dễ theo dõi

#Câu a
print("\nCâu a")
# Tính khoảng cách từ q đến tập train
y_pred = np.zeros(X_train.shape[0])
for j in range(X_train.shape[0]):
    # Sử dụng bình phương khoảng cách để số nguyên vẹn, dễ nhìn (như đề gợi ý)
    y_pred[j] = np.sum(np.power(X_test[0,:] - X_train[j,:], 2))

print("\n1. Bình phương khoảng cách từ q đến T1 -> T6:")
print(y_pred)

# Sắp xếp theo chiều tăng dần khoảng cách
zipped = zip(y_pred, y_train, labels)
res = sorted(zipped, key = lambda x:x[0])

print("\n2. Danh sách điểm huấn luyện sau khi sắp xếp tăng dần:")
for dist, label, name in res:
    print(f"- {name}: d^2 = {int(dist)}, thuộc Lớp {label}")


#b
print("\n\n Câu b")
k = 3

# Lấy k phần tử đầu tiên (k điểm gần nhất)
results_topk = res[:k]

print(f"\n3 điểm láng giềng gần q nhất là:")
for dist, label, name in results_topk:
    print(f"+ {name} (Lớp {label})")

# Đếm số lượng của mỗi class (lớp) trong top k
classes = {}
for _, j, _ in results_topk:
    j = int(j)
    if j not in classes:
        classes[j] = 1
    else:
        classes[j] = classes[j] + 1

print(f"\nKiểm phiếu (Lớp: Số phiếu): {classes}")

# Trả về class có số lượng phiếu nhiều nhất
predicted_class = max(classes, key = classes.get)
print(f"=> Kết luận: Điểm q được phân vào Lớp {predicted_class}")


#c
# Dữ liệu khoảng cách và nhãn đã được sắp xếp tăng dần từ câu a
# Thứ tự điểm: T1, T2, T3, T4, T5, T6
y_train_sorted = [0, 1, 0, 1, 1, 0]
labels_sorted = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6']

print("\n\nCâu c")

# --- TRƯỜNG HỢP k = 4 ---
k1 = 4
classes_k4 = {}

# Lấy 4 phần tử đầu tiên
for i in range(k1):
    lop = int(y_train_sorted[i])
    if lop not in classes_k4:
        classes_k4[lop] = 1
    else:
        classes_k4[lop] = classes_k4[lop] + 1

print(f"\n1. Với k = {k1}, các điểm được xét là: {labels_sorted[:k1]}")
print(f"   Kết quả kiểm phiếu (Lớp: Số phiếu): {classes_k4}")

# Dòng lệnh quyết định trong mã mẫu
lop_quyet_dinh_k4 = max(classes_k4, key=classes_k4.get)
print(f"   => Dòng lệnh max() chọn: Lớp {lop_quyet_dinh_k4} (Do Lớp 0 được chèn vào trước)")


# --- TRƯỜNG HỢP k = 5 ---
k2 = 5
classes_k5 = {}

# Lấy 5 phần tử đầu tiên
for i in range(k2):
    lop = int(y_train_sorted[i])
    if lop not in classes_k5:
        classes_k5[lop] = 1
    else:
        classes_k5[lop] = classes_k5[lop] + 1

print(f"\n2. Khi tăng lên k = {k2}, các điểm được xét là: {labels_sorted[:k2]}")
print(f"   Kết quả kiểm phiếu mới (Lớp: Số phiếu): {classes_k5}")

lop_quyet_dinh_k5 = max(classes_k5, key=classes_k5.get)
print(f"   => Kết quả đổi thành: Lớp {lop_quyet_dinh_k5} (Do Lớp 1 chiếm đa số 3 > 2)")

--- K-Means ---

Câu a
a) Ma trận khoảng cách từ 6 điểm dữ liệu đến 2 tâm C1 và C2:
[[2.24 5.39]
 [2.24 4.12]
 [3.   3.  ]
 [7.07 1.41]
 [6.32 2.  ]
 [8.   2.  ]]

Nhãn được phân cho 6 điểm (0 là C1, 1 là C2):
[0 0 0 1 1 1]

- Giải thích về điểm P3:
  Khoảng cách từ P3 đến C1 và C2 là bằng nhau (đều bằng 3.0).
  Hàm np.argmin() có đặc điểm là sẽ lấy vị trí (index) đầu tiên chứa giá trị nhỏ nhất.
  Vì C1 nằm ở vị trí số 0 nên P3 được xếp vào cụm C1.


Câu b

b) Tọa độ chính xác của 2 tâm cụm mới sau vòng lặp đầu tiên:
[[ 2.          0.33333333]
 [ 7.         -0.33333333]]


Câu c

c) Thuật toán đã hội tụ chưa? -> Chưa hội tụ
- Giải thích:
  Hàm kmeans_has_converged() sẽ kiểm tra xem tọa độ tâm cũ và tâm mới có giống y hệt nhau không.
  Ở đây, tọa độ của 2 tâm đã thay đổi hoàn toàn nên thuật toán chưa thể dừng lại (chưa hội tụ).


--- K-NN ---

Câu a

1. Bình phương khoảng cách từ q đến T1 -> T6:
[ 4.  8.  9. 13. 16. 20.]

2. Danh sách điểm huấn luyện sau khi sắp xếp tăng dần:
- T1: d^2 

**Câu 2(Phần B) câu c**

Khi k = 4 (Hòa phiếu 2-2):

* Mã mẫu chọn: Lớp 0.
* Cơ chế: Dòng lệnh max(classes, key=classes.
get) khi hòa phiếu sẽ ưu tiên chọn lớp được thêm vào từ điển trước. Do điểm gần nhất T1 (Lớp 0) được duyệt trước nên Lớp 0 được chọn.  

Khi tăng lên k = 5:
* Kết quả: CÓ THAY ĐỔI (Chuyển sang Lớp 1).
* Vì sao: Lấy thêm điểm T5 (Lớp 1) , nâng tỉ số lên 3 phiếu cho Lớp 1 và 2 phiếu cho Lớp 0. Lớp 1 thắng vì chiếm đa số (3 > 2).